/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_preferences_window (void);
GtkWidget* create_GOP_window (void);
GtkWidget* create_main_popup (void);
GtkWidget* create_error_dialog (void);
GtkWidget* create_new_file_window (void);
GtkWidget* create_open_file_window (void);
GtkWidget* create_save_file_window (void);
GtkWidget* create_export_file_window (void);
